### ISSUE TITLE
Question should be marked as answered for the user

### ISSUE THREAD

**Issue by Floxo05** [whosFritz/BreakDecider#19]
To increase user experience, you should mark the questions as answered. 

Maybe just add a tick or a cross or the more intuituve way, make the buttons disabled, so you can't even click them.

**Comment by whosFritz** [comment]
wheres the difference to the current system?

**Comment by Floxo05** [comment]
![image](https://github.com/whosFritz/BreakDecider/assets/38435969/6d07c418-bb2b-4311-a8fa-8361df3d7d6e)

Now if you want to vote on a question, that you have already voted, you only get the message "Du hast bereits abgestimmt". I would like to see directly, if i have alredy voted on a question and dont have to click a button, only to see an "error" message.

There comes my idea to disable the buttons, if you have voted, so you see directly, that you can not vote again.
